### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by martin-esparragoza** [alex-battikha/Snake-Game#1]
Put it on heroku for christ sake im too lazy to download the source

**Comment by alex-battikha** [comment]
I haven't finished it yet. There's a few bugs that I'll try and fix tonight. I'll put it up on heroku when I'm done

**Comment by martin-esparragoza** [comment]
AHHHHHHHH WHY ARE YOU SO ACTIVE HOLY CRAP

**Comment by alex-battikha** [comment]
Hahaha

**Comment by martin-esparragoza** [comment]
bruh i dont even use github that much

**Comment by martin-esparragoza** [comment]
90% of my repos are private

**Comment by alex-battikha** [comment]
Bruh do you post more on heroku

**Comment by martin-esparragoza** [comment]
i have like 2 on heroku and they are both private

**Comment by alex-battikha** [comment]
I was wondering why you only have 3 repos lol

**Comment by martin-esparragoza** [comment]
oh ill unprivate some

**Comment by alex-battikha** [comment]
Alrighty, sounds good

**Comment by martin-esparragoza** [comment]
hol up they all 𝐜𝐫𝐢𝐧𝐠𝐞

**Comment by alex-battikha** [comment]
lol, great that's how you know they will be good

**Comment by martin-esparragoza** [comment]
i finished like none of em one of thems a multibox script

**Comment by martin-esparragoza** [comment]
anyway gtg
